
package webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Randon", targetNamespace = "http://webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Randon {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "next", targetNamespace = "http://webservice/", className = "webservice.Next")
    @ResponseWrapper(localName = "nextResponse", targetNamespace = "http://webservice/", className = "webservice.NextResponse")
    @Action(input = "http://webservice/Randon/nextRequest", output = "http://webservice/Randon/nextResponse")
    public double next(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

}
