
package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RandonService", targetNamespace = "http://webservice/", wsdlLocation = "http://localhost:8080/randon?wsdl")
public class RandonService
    extends Service
{

    private final static URL RANDONSERVICE_WSDL_LOCATION;
    private final static WebServiceException RANDONSERVICE_EXCEPTION;
    private final static QName RANDONSERVICE_QNAME = new QName("http://webservice/", "RandonService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/randon?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RANDONSERVICE_WSDL_LOCATION = url;
        RANDONSERVICE_EXCEPTION = e;
    }

    public RandonService() {
        super(__getWsdlLocation(), RANDONSERVICE_QNAME);
    }

    public RandonService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RANDONSERVICE_QNAME, features);
    }

    public RandonService(URL wsdlLocation) {
        super(wsdlLocation, RANDONSERVICE_QNAME);
    }

    public RandonService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RANDONSERVICE_QNAME, features);
    }

    public RandonService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RandonService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Randon
     */
    @WebEndpoint(name = "RandonPort")
    public Randon getRandonPort() {
        return super.getPort(new QName("http://webservice/", "RandonPort"), Randon.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Randon
     */
    @WebEndpoint(name = "RandonPort")
    public Randon getRandonPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice/", "RandonPort"), Randon.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RANDONSERVICE_EXCEPTION!= null) {
            throw RANDONSERVICE_EXCEPTION;
        }
        return RANDONSERVICE_WSDL_LOCATION;
    }

}
